n1 = input('Escreva um número :')
print('vamos saber o número digitado? :')
print(n1)
print('vamos saber o tipo primitivo? :')
print(type(n1))
print('O que você digitou é númérico? :')
print(n1.isnumeric())
print('O que você digitou é alphanumérico? :')
print(n1.isalnum())
print('O que você digitou é alpha (alfabético)? :')
print(n1.isalpha())
print('Está em maiúsculo? :')
print(n1.isupper())
print('Está somente em minúsculo? :')
print(n1.islower())

